### ISSUE TITLE
Errors when running the sample.multiPhate.config file 

### ISSUE THREAD

**Issue by sean-bam** [carolzhou/multiPhATE#7]
I just cloned the master repo and tried running the sample.multiPhate.config file. I get the following error

> Checking files...
Configuration complete.
Preparing to run genecall module...
Calling the gene-call module.
  File "/programs/multiPhATE/GeneCalling/phate_genecallPhage.py", line 413
    print(fileType, ": ", files[fileType], end=' ')
                                                              ^
SyntaxError: invalid syntax
Done!
Preparing command strings for homology searches...
Calling the sequence annotation module.
Traceback (most recent call last):
  File "/programs/multiPhATE/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 87, in <module>
    import phate_fastaSequence  # generic fasta sequence module
  File "/programs/multiPhATE/SequenceAnnotation/phate_fastaSequence.py", line 414
    print("Codon start locations:", end=' ')

Any ideas on how to fix this?

**Comment by carolzhou** [comment]
I believe this error occurs if the code is being run under Python 2.x. Needs to run under Python 3.x. Please verify what version of python you are running, and we can go from there.

Sent from my iPhone

On Aug 6, 2019, at 2:33 PM, sean-bam <notifications@github.com<mailto:notifications@github.com>> wrote:


I just cloned the master repo and tried running the sample.multiPhate.config file. I get the following error

Checking files...
Configuration complete.
Preparing to run genecall module...
Calling the gene-call module.
File "/programs/multiPhATE/GeneCalling/phate_genecallPhage.py", line 413
print(fileType, ": ", files[fileType], end=' ')
^
SyntaxError: invalid syntax
Done!
Preparing command strings for homology searches...
Calling the sequence annotation module.
Traceback (most recent call last):
File "/programs/multiPhATE/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 87, in
import phate_fastaSequence # generic fasta sequence module
File "/programs/multiPhATE/SequenceAnnotation/phate_fastaSequence.py", line 414
print("Codon start locations:", end=' ')

Any ideas on how to fix this?

**Comment by sean-bam** [comment]
That was the problem, thanks!
